[package]
name = "kuhn_cfr_tutorial"
version = "0.1.0"
authors = ["Tadas Subonis <tadas.subonis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
itertools = "0.9"
